apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-frontend
spec:
  # serviceAccountName: {{ .Values.global.serviceaccount.name }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}-deployment
  maxReplicas: 5
  minReplicas: 1
  targetCPUUtilizationPercentage: 50