apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{.Chart.Name }}-deployment
  labels:
    app: lusha
    chart: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      chart: {{ .Chart.Name }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: lusha
        chart: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.global.serviceaccount.name }}
      initContainers:
      - name: init-frontend
        image: alpine
        command: ['sh', '-c', "until nslookup backend-service.default.svc.cluster.local; do echo waiting for backend-service; sleep 1; done"]
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.podPort | int }}
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.service.podPort | int }}
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: BACKEND_HOST
          value: backend-service