apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-statefulset
  labels:
    app: lusha
    chart: {{ .Chart.Name }}
spec:
  serviceName: {{ .Values.service.name }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        app: lusha
        role: mongo
    spec:
      serviceAccountName: {{ .Values.global.serviceaccount.name }}
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.mongo.image.name }}:{{ .Values.mongo.image.version }}"
          ports:
            - containerPort: {{ .Values.mongo.port }}
          volumeMounts:
            - name: mongodb-persistent-storage-claim
              mountPath: /data/db
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: {{ .Values.global.mongo.username }}
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: {{ .Values.global.mongo.password }}
          - name: MONGO_INITDB_DATABASE
            value: {{ .Values.global.mongo.dbname }}
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Mi