ingress:
  name: lusha-ingress

service:
  name: frontend-service
  externalPort: 8080
  internalPort: 8080

global:
  serviceaccount:
    name: users-sa
  mongo:
    username: lushaUser
    password: lushaPassword
    dbname: usersdb