apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  labels:
    app: lusha
    chart: {{ .Chart.Name }}
type: Opaque
data:
  username: {{ .Values.global.mongo.username | b64enc }}
  password: {{ .Values.global.mongo.password | b64enc }}
  dbname: {{ .Values.global.mongo.dbname | b64enc }}