apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Chart.Name }}-deployment
  labels:
    app: lusha
    chart: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: lusha
      chart: {{ .Chart.Name }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: lusha
        chart: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.service.podPort | int }}
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.service.svcPort | int }}
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.service.svcPort | int }}
        env:
        - name: MONGO_DB_NAME
          value: mongodb-service
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        