apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Chart.Name }}-deployment
  labels:
    app: lusha
    chart: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: lusha
      chart: {{ .Chart.Name }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: lusha
        chart: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.global.serviceaccount.name }}
      initContainers:
      - name: init-backend
        image: alpine
        command: ['sh', '-c', "until nslookup mongodb-service.default.svc.cluster.local; do echo waiting for mongodb-service; sleep 0.1; done"]
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.service.podPort | int }}
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.service.svcPort | int }}
        resources:
          requests:
            cpu: 200m
        env:
        - name: MONGO_HOST
          value: mongodb-service
        - name: MONGO_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: dbname
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password